services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [medusa_net]

  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: [medusa_net]

  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@medusa_postgres:5432/medusa-store
      REDIS_URL: redis://medusa_redis:6379
      STORE_CORS: "*"
      ADMIN_CORS: "*"
      AUTH_CORS: "*"
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
    volumes:
      - .:/server
      - /server/node_modules
    command: ["/usr/bin/env","bash","-lc","/usr/local/bin/start.sh"]
    networks: [medusa_net]

volumes:
  postgres_data:

networks:
  medusa_net:
    driver: bridge
    
